### ISSUE TITLE
Cannot download this

### ISSUE THREAD

**Issue by jnothstine** [JakeGinnivan/XamlAttributeOrderingCodeCleanup#1]
When I try to Install this via ReSharper - Manage Extensions, I get a 404 error.  This looks like a plugin that I would really like to have.  Not sure how to install it though.

**Comment by JakeGinnivan** [comment]
Well that's annoying.. It used to work :)

Will fix.

**Comment by derigel23** [comment]
Fixed at the gallery side.

**Comment by JakeGinnivan** [comment]
Thanks @derigel23
